// Generated by CoffeeScript 1.6.3
(function() {
  var Sazed;

  Sazed = (function() {
    Sazed.prototype._translatePath = function(path) {
      if (path == null) {
        path = document.location.pathname;
      }
      path = path.replace(/\.html/, '.md');
      if (path.match(/\/$/)) {
        path = path.concat('index.md');
      }
      return path;
    };

    function Sazed(options) {
      var _ref;
      this.options = options != null ? options : {};
      this.options['parser'] = (_ref = this.options['parser']) != null ? _ref : require('marked');
      if (this.options['repo'] == null) {
        throw "No repo provided";
      }
      if (this.options['container'] == null) {
        throw 'No container given';
      }
      if (typeof this.options['container'] === 'String') {
        this.container = document.getElementById(this.options['container']);
      }
    }

    Sazed.prototype.edit = function(file_path) {};

    return Sazed;

  })();

  module.exports = Sazed;

}).call(this);
